//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPrice
    {
        public int ProductId { get; set; }
        public Nullable<int> MenuId { get; set; }
        public string Size { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual tblMenu tblMenu { get; set; }
    }
}
